import React, { Component } from 'react';

class Constructor extends Component {
  constructor(props) {
    super(props);
    console.log('This is generated by react Constructor');   
  }
  onClickMethod() {
    console.log('This is the generated by methods');
  }
  onClickFunction = () => {
    console.log('This is the generated by arrow function');
  }
  render() {
    		return(
    		<div>
    		 <button onClick={this.onClickFunction}>Arrow Function</button>
    		 <button onClick={this.onClickMethod}>Method</button>
    		 </div>
  );}
}		
export default Constructor;